Fixes #29093 - change from superficial copy to deep copy of fields
theforeman/hammer-cli pull request #348
Opened 2021-07-13 09:11 UTC by adiabramovitch

2021-07-13 13:03 UTC, yifatmakias requested changes
Thanks @adiabramovitch ,
Notice that the hammer_cli_foreman tests are failing with this error:
![image](https://user-images.githubusercontent.com/42476762/125456332-6eb858f7-430b-4a0d-a4c3-33ec4d624f06.png)

2021-07-20 15:16 UTC, ofedoren commented on lib/hammer_cli/options/option_family.rb
> -        @creator = options[:creator] || Class.new(HammerCLI::Apipie::Command)
FYI: I'm currently working on a little bit different approach for option creation and this anonymous class will disappear :) So, :+1: for the solution, but it should wait a bit before we get rid of this class.

2021-08-12 14:17 UTC, ofedoren approved these changes
Thanks, @adiabramovitch! Since this change doesn't break tests for plugins anymore we can finally merge it :)

2021-08-12 14:18 UTC, merged

2021-08-16 12:53 UTC, ekohl commented
Looks like this broke nightly again, just like in https://github.com/theforeman/hammer-cli/pull/345#issuecomment-852052250: https://ci.theforeman.org/job/foreman-nightly-rpm-pipeline/1160/tapResults/ 
```tap
not ok 6 import motd puppet class
# (in test file fb-test-puppet.bats, line 64)
#   `hammer proxy import-classes --name $(hostname -f)' failed with status 70
# Error: singleton can't be dumped
```

2021-08-16 13:39 UTC, ofedoren commented
> Looks like this broke nightly again, just like in [#345 (comment)](https://github.com/theforeman/hammer-cli/pull/345#issuecomment-852052250): https://ci.theforeman.org/job/foreman-nightly-rpm-pipeline/1160/tapResults/

@ekohl, yeap, I'm aware of that: https://github.com/theforeman/hammer-cli/pull/353

2021-08-16 13:43 UTC, ekohl commented
Thanks!